-- Run this in the Supabase SQL Editor to set up your table

create table city_trends (
  id bigint generated by default as identity primary key,
  rank integer,
  city text not null,
  country text not null,
  trend_direction text check (trend_direction in ('rising', 'cooling', 'stable')),
  index_score integer,
  sparkline_data numeric[], -- Array of numbers
  insight text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) is good practice, but for a public read-only dashboard:
alter table city_trends enable row level security;

-- Create a policy to allow public read access
create policy "Enable read access for all users" on city_trends for select using (true);

-- Create a policy to allow insert only for authenticated users (or you/setup script)
-- For simplicity in this demo, we'll allow public insert to run the seed script easily from the browser,
-- BUT you should disable this after seeding!
create policy "Enable insert for all users (TEMPORARY)" on city_trends for insert with check (true);
