import { ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export type TrendDirection = 'rising' | 'cooling' | 'stable';

export interface CityTrend {
  rank: number;
  city: string;
  country: string;
  trendDirection: TrendDirection;
  indexScore: number;
  sparklineData: number[]; // Last 6 months
  insight: string;
}

export const mockCities: CityTrend[] = [
  {
    rank: 1,
    city: "Kyoto",
    country: "Japan",
    trendDirection: "rising",
    indexScore: 98,
    sparklineData: [45, 52, 68, 74, 85, 98],
    insight: "Cherry blossom inquiries up 120%",
  },
  {
    rank: 2,
    city: "Medellín",
    country: "Colombia",
    trendDirection: "rising",
    indexScore: 94,
    sparklineData: [60, 65, 72, 80, 88, 94],
    insight: "Digital nomad visas approved +40%",
  },
  {
    rank: 3,
    city: "Tromsø",
    country: "Norway",
    trendDirection: "rising",
    indexScore: 91,
    sparklineData: [30, 45, 60, 75, 85, 91],
    insight: "Northern Lights season peak demand",
  },
  {
    rank: 4,
    city: "Cape Town",
    country: "South Africa",
    trendDirection: "stable",
    indexScore: 89,
    sparklineData: [88, 90, 89, 88, 90, 89],
    insight: "Consistent luxury booking volume",
  },
  {
    rank: 5,
    city: "Seoul",
    country: "South Korea",
    trendDirection: "rising",
    indexScore: 87,
    sparklineData: [70, 75, 78, 82, 85, 87],
    insight: "K-Pop tourism driving 20-30s demo",
  },
  {
    rank: 6,
    city: "Tulum",
    country: "Mexico",
    trendDirection: "cooling",
    indexScore: 84,
    sparklineData: [95, 92, 88, 85, 82, 84],
    insight: "Overcrowding sentiment in reviews",
  },
  {
    rank: 7,
    city: "Lisbon",
    country: "Portugal",
    trendDirection: "stable",
    indexScore: 82,
    sparklineData: [80, 81, 83, 82, 81, 82],
    insight: "Steady tech conference traffic",
  },
  {
    rank: 8,
    city: "Ho Chi Minh City",
    country: "Vietnam",
    trendDirection: "rising",
    indexScore: 80,
    sparklineData: [50, 60, 65, 70, 75, 80],
    insight: "Affordable luxury sector booming",
  },
  {
    rank: 9,
    city: "Mykonos",
    country: "Greece",
    trendDirection: "cooling",
    indexScore: 78,
    sparklineData: [90, 88, 85, 82, 80, 78],
    insight: "Price hikes reducing budget stays",
  },
  {
    rank: 10,
    city: "Bali",
    country: "Indonesia",
    trendDirection: "stable",
    indexScore: 76,
    sparklineData: [75, 76, 75, 77, 76, 76],
    insight: "Digital nomad saturation point",
  },
  {
    rank: 11,
    city: "Buenos Aires",
    country: "Argentina",
    trendDirection: "rising",
    indexScore: 74,
    sparklineData: [50, 55, 60, 65, 70, 74],
    insight: "Value-driven travel surging",
  },
  {
    rank: 12,
    city: "Istanbul",
    country: "Turkey",
    trendDirection: "rising",
    indexScore: 72,
    sparklineData: [60, 62, 65, 68, 70, 72],
    insight: "Hair transplant medical tourism up",
  },
  {
    rank: 13,
    city: "Dubrovnik",
    country: "Croatia",
    trendDirection: "cooling",
    indexScore: 70,
    sparklineData: [85, 82, 80, 78, 75, 70],
    insight: "Cruise restrictions impacting volume",
  },
  {
    rank: 14,
    city: "Marrakech",
    country: "Morocco",
    trendDirection: "rising",
    indexScore: 68,
    sparklineData: [55, 58, 60, 62, 65, 68],
    insight: "Luxury riad bookings increasing",
  },
  {
    rank: 15,
    city: "Copenhagen",
    country: "Denmark",
    trendDirection: "stable",
    indexScore: 66,
    sparklineData: [65, 66, 67, 65, 66, 66],
    insight: "Sustainable travel hub steady",
  },
  {
    rank: 16,
    city: "Austin",
    country: "USA",
    trendDirection: "cooling",
    indexScore: 64,
    sparklineData: [80, 75, 72, 70, 68, 64],
    insight: "Festival off-season dip",
  },
  {
    rank: 17,
    city: "Bangkok",
    country: "Thailand",
    trendDirection: "rising",
    indexScore: 63,
    sparklineData: [50, 52, 55, 58, 60, 63],
    insight: "Street food recognition driving traffic",
  },
  {
    rank: 18,
    city: "Paris",
    country: "France",
    trendDirection: "stable",
    indexScore: 62,
    sparklineData: [62, 63, 61, 62, 62, 62],
    insight: "Post-Olympics normalization",
  },
  {
    rank: 19,
    city: "Reykjavik",
    country: "Iceland",
    trendDirection: "cooling",
    indexScore: 60,
    sparklineData: [75, 70, 68, 65, 62, 60],
    insight: "Volcanic activity concerns",
  },
  {
    rank: 20,
    city: "Venice",
    country: "Italy",
    trendDirection: "cooling",
    indexScore: 58,
    sparklineData: [80, 75, 70, 65, 60, 58],
    insight: "Entry fee discouraging day trips",
  },
  {
    rank: 21,
    city: "Oaxaca",
    country: "Mexico",
    trendDirection: "rising",
    indexScore: 57,
    sparklineData: [40, 45, 48, 50, 55, 57],
    insight: "Culinary tourism explosion",
  },
  {
    rank: 22,
    city: "Prague",
    country: "Czech Republic",
    trendDirection: "stable",
    indexScore: 55,
    sparklineData: [55, 56, 54, 55, 55, 55],
    insight: "Stag party regulation effect",
  },
  {
    rank: 23,
    city: "Amsterdam",
    country: "Netherlands",
    trendDirection: "cooling",
    indexScore: 53,
    sparklineData: [70, 65, 62, 60, 55, 53],
    insight: "Hotel construction moratorium",
  },
  {
    rank: 24,
    city: "Barcelona",
    country: "Spain",
    trendDirection: "stable",
    indexScore: 52,
    sparklineData: [50, 51, 53, 52, 51, 52],
    insight: "Water restrictions creating pause",
  },
  {
    rank: 25,
    city: "Dubai",
    country: "UAE",
    trendDirection: "rising",
    indexScore: 50,
    sparklineData: [40, 42, 45, 46, 48, 50],
    insight: "Stopover program gaining traction",
  },
  {
    rank: 26,
    city: "Singapore",
    country: "Singapore",
    trendDirection: "stable",
    indexScore: 48,
    sparklineData: [48, 49, 48, 47, 48, 48],
    insight: "Business travel plateau",
  },
  {
    rank: 27,
    city: "Sydney",
    country: "Australia",
    trendDirection: "cooling",
    indexScore: 45,
    sparklineData: [60, 58, 55, 52, 48, 45],
    insight: "Flight costs remaining high",
  },
  {
    rank: 28,
    city: "London",
    country: "UK",
    trendDirection: "stable",
    indexScore: 42,
    sparklineData: [42, 43, 41, 42, 42, 42],
    insight: "Slight dip in summer bookings",
  },
  {
    rank: 29,
    city: "New York",
    country: "USA",
    trendDirection: "stable",
    indexScore: 40,
    sparklineData: [40, 41, 39, 40, 40, 40],
    insight: "Hotel prices limiting growth",
  },
  {
    rank: 30,
    city: "San Francisco",
    country: "USA",
    trendDirection: "rising",
    indexScore: 35,
    sparklineData: [20, 25, 28, 30, 32, 35],
    insight: "Tech convention circuit returning",
  },
];
